version: "3.9"
services:
  flaskappc:
    build: .
    ports:
      - "5000:5000"
    environment: 
        FLASK_DEBUG: "True"
        FLASK_APP: "8inf349"
  redisc:
    image: redis:alpine
    environment: 
        REDIS_URL: redis://localhost
  postgresc:
    image: postgres:12
    restart: always
    environment: 
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "pass"
        POSTGRES_DB: "8inf349"
        POSTGRES_HOST_AUTH_METHOD: trust
  adminerc:
    image: adminer
    restart: always
    ports:
        - 8080:8080