version: "3.9"
services:
  db:
    image: postgres:12
    restart: always
    environment: 
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "pass"
        POSTGRES_DB: "8inf349"
        POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - volume-postgres:/var/lib/postgressql/data
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    environment: 
        FLASK_DEBUG: "True"
        FLASK_APP: "8inf349"
  redis:
    image: redis:alpine
    restart: always
    environment: 
        REDIS_URL: redis://redis
    ports:
      - 6379:6379
    expose:
      - '6379'
  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
volumes:
  volume-postgres: